# Generated by Django 6.0.2 on 2026-03-08 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=350)),
                (
                    "zip_code",
                    models.CharField(
                        default="00000", max_length=10, verbose_name="zip code"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=800, null=True)),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="cover_images/"),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("NON_PROFIT", "Non-Profit"),
                            ("COMMUNITY_GROUP", "Community Group"),
                            ("BUSINESS", "Farm"),
                        ],
                        default="BUSINESS",
                        max_length=20,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="organizations", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        related_name="owned_organizations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
