# Generated by Django 6.0.2 on 2026-03-08 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
