# Generated by Django 6.0.2 on 2026-03-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_remove_organization_owners_organization_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
